blank_issues_enabled: false
contact_links:
  - name: Have any issues to discuss regarding Coding Blocks?
    url: https://gitter.im/coding-blocks/boss-2020-lobby
    about: Join us on Gitter and meet members, contributors and the owners!
